### ISSUE TITLE
Should constructors take max cardinality and error instead?

### ISSUE THREAD

**Issue by mbana** [armon/hlld#8]
Howdy. Firstly, nice talk on HyperLogLog.

I am reading the "Loglog Counting of Large Cardinalities", but I guess the idea still applies, and I wonder why most implementations don't just take in the following and just infer the required values:

- Hash function along with size of output.
- Desired error rate.
- N<sub>max</sub>.

I guess I am reading the paper wrong but it seems like the error rate, memory units (registers) etc. are a function of what I just listed? Not too sure ... please correct me if I am wrong. My aim is just to stop people manual calculating the parameters required - make it to automatic.

**Comment by armon** [comment]
@mbana That is the approach hlld takes exactly. You basically give it the target error rate (`eps` to `create` command) and it computes everything else as necessary. You can specify the `precision` instead if you really want that level of control, but its not necessary. In fact, even the `eps` defaults to like 1.2% or something, so really you can avoid all parameters. Closing, but please re-open if you have a question.
